from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '044b7686d7a5'
down_revision = '9d75c5300cae'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_date', sa.Date(), nullable=False))
        # Добавляем имя внешнего ключа
        batch_op.create_foreign_key('fk_analytics_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        # Указываем имя внешнего ключа при удалении
        batch_op.drop_constraint('fk_analytics_user_id', type_='foreignkey')
        batch_op.drop_column('use_date')

    # ### end Alembic commands ###
