"""empty message

Revision ID: fb5fa5b9eb7e
Revises: 044b7686d7a5
Create Date: 2025-02-10 00:22:36.398645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5fa5b9eb7e'
down_revision = '044b7686d7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('delete_date', sa.Date(), nullable=True))
        batch_op.drop_column('use_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_date', sa.DATE(), nullable=False))
        batch_op.drop_column('delete_date')
        batch_op.drop_column('add_date')

    # ### end Alembic commands ###
