"""empty message

Revision ID: fc936ef9fa78
Revises: ecdecd82c58c
Create Date: 2025-02-10 19:59:13.056519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc936ef9fa78'
down_revision = 'ecdecd82c58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')
        batch_op.drop_column('manufacture_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacture_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('expiration_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
